### PR TITLE
Update Readme.md ⇒ Section Installation

### PR DESCRIPTION
**Pull request by xstable**
Add section to describe how to install this component

### CODE REVIEW

**Comment by gianpaj** [comment]
there's already such section:
https://github.com/inProgress-team/react-native-youtube#installation

**Comment by xstable** [comment]
Ok, need to digg deep to found it :)
Would be really user-friendly, if we restructure the page and put it to the top (maybe with a short navigation-tree to each headline)

**Comment by davidohayon669** [comment]
#352

**Comment by hossamnasser938** [comment]
This should be merged. In android, it did not work until I linked it through ` react-native link react-native-youtube ` so why this is not mentioned in the readme!!

**Pull request closed without merging**
