### PR TITLE
Android fullscreen fix

### LINKED ISSUE #114: Android FullScreen Hardware Back Button locks orientation to landscape
When user makes the player full screen and quits via pressing hardware back button, orientation locks to landscape. In addition to that, if user quits and kills the app, he sees the video player full screen just as it was left.

I'm using the latest version of react-native-youtube and RN 0.40

### PR DESCRIPTION
**Pull request by lucianomlima**
Resolves the issue with fullscreen on Android when close vídeo by device back button.
Fix #114

### CODE REVIEW

**Comment by davidohayon669** [comment]
Does this happens also on the v1 branch?
Can you resolve it for the v1 branch as well?
This branch will pretty soon be the next production version

**Comment by lucianomlima** [comment]
I'll check and answer later

**Comment by lucianomlima** [comment]
@davidohayon669 I checked the v1 branch and for now my PR only fix issue on master branch.
v1 branch have a different organization (and have a ReactModule).
But I test the v1 branch and the problems persist. When open a video in fullscreen and press device back button, the orientation blocks on landscape.
I'll send a PR to branch v1 tomorrow.

This PR, configures setFullscreenControlFlags on YouTubePlayer and reset the orientation to device default.

Question, I see that in v1 branch was removed onFullscreenListener. What is the reason?

**Comment by davidohayon669** [comment]
No special reason, we can get it back. Its just that I removed a lot of stuff to have cleaner code so I can apply features more smart

**Comment by davidohayon669** [comment]
v0.x is history

**Comment by ziyafenn** [comment]
Was it never merged? The problem still exists with android hardware button.

**Pull request closed without merging**
