### PR TITLE
Add typescript definition file

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by NoelDeMartin** [comment]
@jujumoz How come this is not available for v1.1.0?

**Comment by jsamr** [comment]
@davidohayon669 Can you investigate?

**Comment by davidohayon669** [comment]
@jsamr investigate what?

**Comment by jsamr** [comment]
@davidohayon669 This `index.d.ts` file has vanished from master. We wonder how and why!

**Comment by davidohayon669** [comment]
ok

**Pull request merged**
