### PR TITLE
Fix JS events on Android, fix rnpm, and clean up unnecessary bits

### PR DESCRIPTION
**Pull request by mikelambert**

### CODE REVIEW

**Comment by davidohayon669** [comment]
Is anybody considering this PR? Seems like good stuff

**Comment by juangl** [comment]
will it be merged? is this project still alive?

**Comment by sibelius** [comment]
@inProgress-team this looks good to me

could u guys add more contributor to make this project move faster?

cc @jujumoz

**Comment by jujumoz** [comment]
Thank you @mikelambert for this PR, it looks great !
Just one thing, seekTo doesn't work anymore on my side. I know the module was not the best way, but with @ReactMethod, I can't reach it. How do you manage to use it with this code ?

**Comment by mikelambert** [comment]
Ahh, I don't use seekTo. It's been a few months since I wrote this code, so I'm not sure what my thinking was at the time.

If you change `this.refs.youtubePlayer.seekTo` to `this._root.seekTo` in `YouTube.android.js`, does it work?

**Comment by jujumoz** [comment]
I did find a solution for seekTo ! I will add those changes asap to clean the all code.

**Comment by mikelambert** [comment]
If you submit a pull request against my repo, I will be happy to merge it in, and add it to this pull request against inProgress-team's version.

**Comment by mikelambert** [comment]
Hey there, is there anything else you need me to do here for this code? (with respect to seekTo, or anything else?) Thanks!

**Comment by edencakir** [comment]
Is this hilarious repo abandoned?

**Comment by jujumoz** [comment]
@mikelambert Could you just resolve the conflicts by yourself before I merge it ? thanks !

**Comment by mikelambert** [comment]
Okay, merged, and seems to work on both iOS and Android for me now.

Looking at the changelist now, what code is being added/changed, it looks like the accurate description now would be:
- Move dir to android/, so that it works with rnpm
- Fixup consistency on some of the event callbacks on android/ios
- Remove extraneous passing around of context for stuff we can deduce automatically

Tested to verify everything (of the functionality I use) works as expected within my app that uses react-native-youtube.

**Comment by safweb89** [comment]
"playsInline" is not working for me guys can u please send me a detailed HOWTO so i can install it properly.
i want to use youtube player in scrollView on android platform but i got so many problems can u help me please

**Pull request merged**
