### PR TITLE
Support React Native 0.40.x header imports

### PR DESCRIPTION
**Pull request by georgiana-gligor**
* fixes inProgress-team/react-native-youtube#88

### CODE REVIEW

**Comment by andon** [comment]
Better if the library continues to work with RN < 0.40:
https://twitter.com/atticoos/status/825435275887276033

**Comment by max-mykhailenko** [comment]
@georgiana-gligor please fix compatibility

**Comment by georgiana-gligor** [comment]
Hi @max-mykhailenko I'm not sure I completely understand what you mean. Do you refer to setting `"version": "0.9.0"` in `package.json instead of `0.8.1`? Or do you mean something completely different?

**Comment by max-mykhailenko** [comment]
@georgiana-gligor  @andon told that better don't remove compatibility and code example for this
c3si8n-w8aapp89

**Comment by georgiana-gligor** [comment]
Thank you for the patience @max-mykhailenko . I have updated the pull request to reflect this.

**Comment by wcandillon** [comment]
I tried this PR and it seems to be working great 🎉

**Comment by max-mykhailenko** [comment]
Who can release this?

**Comment by max-mykhailenko** [comment]
@paramaggarwal please release this PR

**Comment by jujumoz** [comment]
Can you just resolve the conflicts by yourself before I merge it ? thanks !

**Comment by salmankhann** [comment]
@jujumoz could you release 0.8.1 to npm?

**Comment by jujumoz** [comment]
@salmankhann done !

**Comment by salmankhann** [comment]
@jujumoz there seems to be a problem because the latest version on npm is still 0.8.0. Could you please check?

**Comment by max-mykhailenko** [comment]
@jujumoz have same problem, don't see 0.8.1 on npm

**Comment by Naoto-Ida** [comment]
I still can't see it with `npm view react-native-youtube versions`.

**Comment by rdougan** [comment]
@jujumoz still not released. I don't see the 0.8.1 tag - perhaps that is why?

**Comment by julienaba** [comment]
Should be working now, I published 0.8.1 on npm. ;)
If anyone have time to update the "readme.md", please feel free !

**Comment by jujumoz** [comment]
@max-mykhailenko , @Naoto-Ida , @rdougan , it should be working now, I published 0.8.1 on npm. ;)
Keep me in touch and sorry for the delay.
If anyone has time to update the README, please feel free !

**Pull request merged**
