### PR TITLE
Fixed/added support for inline playback support on Android

### LINKED ISSUE #83: On Android, `YouTube` component which is in `ScrollView` stops playback.
## Summary

On Android, `YouTube` component which is in `ScrollView` stops playback.
## Detail

On Android, if `YouTube` component puts in ReactNative `ScrollView` component, playback is terminated.  `adb logcat` says:

```
10-14 11:23:25.977 23083 23083 W YouTubeAndroidPlayerAPI: YouTube video playback stopped due to unauthorized overlay on top of player. The YouTubePlayerView is not contained inside its ancestor android.widget.FrameLayout{fcacd54 V.E...... ......I. 0,0-0,0}. The distances between the ancestor's edges and that of the YouTubePlayerView is: left: 0, top: 0, right: -1794, bottom: -1080 (these should all be positive).
```

You can reproduce it by `Example/index.android.js` with
modification such as:

```
      <ScrollView
        style={{width: 520, height: 500}}
        <YouTube
           (suppress...)
        />
      </ScrollView>
```

You can replace `style` of `ScrollView` to any, but you have to assign some scrollable area. 

This code works well on any iOS devices.
## Information

ReactNative: v0.35.0
react-native-youtube: v0.8.0
Device: Nexus 5X / Android 7.0(NBD90W)

### PR DESCRIPTION
**Pull request by IjzerenHein**
The prop `playsInline` doesn't work on Android. After inspecting I found that it is removed entirely from the props in `YouYube.android.js` (at the bottom). After further investigation I found that inline playback support is working very poorly. This pull requests adds proper inline playback handling for Android. It addresses the following issues:

- fix full-screen mode always started on load when play is false
- cue video when play is false so you can tap it to start the video
- start full-screen mode when video starts playing and inline is not enabled
- exit full-screen mode when video is ended and inline is enabled
- stop video from playing when exiting full-screen and inline is not enabled
- pause video playback when videoId prop is reset
- fix, don't start playback of video when videoId is changed but play is false
- start full-screen when setting play to true and inline is not enabled
- emit 'loaded' event when video has loaded
- emit 'fullscreenMode' and 'windowMode' events when entering/leaving fullscreen

This should fix the following error (which I was experiencing as well): #82  

Also, I noticed that because of the full-screen mode it often showed the dreaded "YouTube video playback stopped due to unauthorized overlay on top of player" bug. This is also fixed now, so should very likely fix #83 as well.

Example of inline video playback on Android:

video

Let me know if I can do anything to speed up the process of getting this accepted.

cheers, Hein

### CODE REVIEW

**Comment by jujumoz** [comment]
Sounds good but your code leads to a black screen for the YouTube component for me when I use playInline = true ... any idea ? 
(I used to use the trick of fullscreen, no fullscreen to avoid this problem of "YouTube video playback stopped due to unauthorized overlay on top of player." until now)

**Comment by IjzerenHein** [comment]
So I've been seeing that problem as well. It's quite reproducible on release builds for me and a lot harder on debug builds. It seems that the component sometimes needs an extra layout.. I found one workaround which consistently fixes the problem. What I do is, after the video has been loaded (loaded event was added in this PR), I force a relayout of the YouTube component, by changing the width by 1 pixel. It's a dirty hack really, but you don't see it visually and it fixes it. I've described the workaround code here:
https://github.com/inProgress-team/react-native-youtube/issues/74#issuecomment-265847311

I've tried for two days for creating a solution in the native code (e.g. by forcing a re-layout on the RelativeLayout) but was unable to find any solutions there.

**Comment by IjzerenHein** [comment]
Hey guys. So I'd really love to see this get pulled in the main branch. Is there anything I can help with to make that happen? I know there is the black screen/no controls/layout messed up issue. But frankly I can also make that happen when not using inline (by exiting fullscreen).
Also shall I resolve the merge conflicts? Let me know.
cheers, Hein

**Comment by jujumoz** [comment]
We still need to find a way to avoid this black screen problem to add the inline option. I will take time to work on it in the next few days.

**Comment by IjzerenHein** [comment]
Awesome! If I can be of any help let me know.

**Comment by edencakir** [comment]
any news?

**Comment by IjzerenHein** [comment]
Hi, I've fixed the conflicts, really hoping this can get accepted.
Best regards

**Comment by IjzerenHein** [comment]
Awesome, thanks!

**Comment by edencakir** [comment]
@IjzerenHein I'm still facing the same issue on Android. Switched to master repo after this merge, rn version: 0.40

**Comment by IjzerenHein** [comment]
@edencakir Which issue is that?

**Comment by edencakir** [comment]
@IjzerenHein Inline playback  - video stops playing after 1 second or so, and works only when its fullscreen

**Comment by IjzerenHein** [comment]
@edencakir Thanks for elaborating. Was asking because there were multiple issues addressed in this PR. Could you try the workaround I described in #74 and see whether that works for you?

**Comment by IjzerenHein** [comment]
@edencakir Also, have you checked the log output in Android studio? What error are you seeing there?

**Comment by edencakir** [comment]
@IjzerenHein I haven't done any logging in Android studio ever, only chrome and ios. `react-native log-android` is this what you're recommending?

I'll try the workaround in #74 tomorrow.

**Comment by IjzerenHein** [comment]
@edencakir I'm not sure if that command logs all the native logs and exceptions (which is what you want in this case). I just launch Android studio after putting the debug version of my app on the Android phone, and select the device and the views logs in the bottom part of the Android studio UI.

**Comment by edencakir** [comment]
Alright thank you a lot, I'll let you know my progress.

**Comment by edencakir** [comment]
```
W/YouTubeAndroidPlayerAPI: YouTube video playback stopped due to the player's view being too small. The YouTubePlayerView is 0dp wide (minimum is 200dp) and 0dp high (minimum is 110dp).
```

This is what I get from Android Studio logging. @IjzerenHein

**Comment by edencakir** [comment]
@IjzerenHein I implemented your #74 solution, however YouTube player doesn't render, except hot reloading changes. Can you share the code where you call <VideoPlayer/>

**Comment by edencakir** [comment]
And this is what I get from your implementation #74 @IjzerenHein
```
W/YouTubeAndroidPlayerAPI: YouTube video playback stopped due to unauthorized overlay on top of player. The YouTubePlayerView is obscured by 
com.facebook.react.views.view.ReactViewGroup{3714d026 V.E..... ........ 0,0-1080,1701 #39}. 
YouTubePlayerView is completely covered, with the distance in px between each edge of the obscuring view and the YouTubePlayerView being: left: 0, top: 162, right: 0, bottom: 769..
```

**Comment by IjzerenHein** [comment]
@edencakir These are the styles (nothing special..):

```
const styles = StyleSheet.create({
	container: {
		justifyContent: 'center',
		alignItems: 'center'
	}
});
```

The containing Component does pass in additional styles to the VideoPlayer component. What happens if you pass in a fixed width and height?

**Comment by raymondctc** [comment]
I encountered the same problem also

```
02-20 13:53:29.538 15801-15801/com.testproj W/YouTubeAndroidPlayerAPI: YouTube video playback stopped due to unauthorized overlay on top of player. The YouTubePlayerView is not contained inside its ancestor android.widget.FrameLayout{cc74690 V.E...... ......I. 0,0-0,0}. The distances between the ancestor's edges and that of the YouTubePlayerView is: left: 0, top: 0, right: 0, bottom: 0 (these should all be positive).
```

I can see there's a spinner circle. But after that, just a black screen. It's not even able to display a thumbnail or other controls

Demo: https://youtu.be/o2-085JX20g

Here is my code, RN 0.41

```jsx
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import YouTube from 'react-native-youtube'

export default class TestProj extends Component {
  render() {
    return (
      <View style={styles.container}>
        <YouTube
          ref="youtubePlayer"
          videoId="KVZ-P-ZI6W4" 
          apiKey={'MY_API_KEY'}
          play={true}           
          hidden={false}        
          playsInline={true}    
          loop={false}          

          onReady={(e)=>{this.setState({isReady: true})}}
          onChangeState={(e)=>{this.setState({status: e.state})}}
          onChangeQuality={(e)=>{this.setState({quality: e.quality})}}
          onError={(e)=>{this.setState({error: e.error})}}
          onProgress={(e)=>{this.setState({currentTime: e.currentTime, duration: e.duration})}}

          style={{alignSelf: 'stretch', height: 300, backgroundColor: 'black'}}
        />
      </View>
      
    );
  }
}

const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center'
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('TestProj', () => TestProj);
```

**Comment by IjzerenHein** [comment]
I'll try to repro

**Comment by raymondctc** [comment]
Update: I just found an interesting fact is that after I rotate the device and the YouTube player loaded properly with the code above. It's just won't load on first launch. No idea why 😐

**Comment by jayprakash1** [comment]
I fixed "unauthorized overlay" issue by making changes for drawer code which is using https://github.com/root-two/react-native-drawer. Added the below parameter for drawer component
`styles={{
  mainOverlay: {
    height: 0,
    width: 0
  }
}}`

**Comment by edencakir** [comment]
@jayprakash1 wow that's a weird but somehow attractive theory. I'll be trying this in a week

**Comment by padupuy** [comment]
@jayprakash1 Your solution works really well, thanks !

**Pull request merged**
